services:
  postgres:
    image: postgres:16-alpine
    container_name: system-project-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medflow
      POSTGRES_USER: medflow_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medflow_user -d medflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4
    container_name: system-project-adminer
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  postgres_data:
