import { AppointmentStatus, Role } from '../../generated/prisma/client';
import { AuditService } from '../audit/audit.service';
import { NotificationsService } from '../notifications/notifications.service';
import { PrismaService } from '../prisma/prisma.service';
import { CreateAppointmentDto } from './dto/create-appointment.dto';
export declare class AppointmentsService {
    private readonly prisma;
    private readonly notificationsService;
    private readonly auditService;
    constructor(prisma: PrismaService, notificationsService: NotificationsService, auditService: AuditService);
    createForPatient(patientId: string, dto: CreateAppointmentDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        doctorId: string;
        status: AppointmentStatus;
        scheduledAt: Date | null;
        reason: string | null;
        preferredDateFrom: Date | null;
        preferredDateTo: Date | null;
        preferredTimeNote: string | null;
        requiresLab: boolean;
        labFlowLocked: boolean;
    }>;
    listMine(userId: string, role: Role): Promise<{
        doctorSnapshot: {
            id: string;
            fullName: string | null;
            email: string;
        };
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        doctorId: string;
        status: AppointmentStatus;
        scheduledAt: Date | null;
        reason: string | null;
        preferredDateFrom: Date | null;
        preferredDateTo: Date | null;
        preferredTimeNote: string | null;
        requiresLab: boolean;
        labFlowLocked: boolean;
    }[] | {
        patientSnapshot: {
            id: string;
            fullName: string | null;
            email: string;
            profile: {
                id: string;
                phone: string | null;
                address: string | null;
                createdAt: Date;
                updatedAt: Date;
                patientId: string;
                dateOfBirth: Date | null;
                gender: string | null;
                allergies: string | null;
                chronicConditions: string | null;
                currentMedications: string | null;
                emergencyContactName: string | null;
                emergencyContactPhone: string | null;
                emergencyContactRelation: string | null;
            } | null;
        };
        patientHistorySummary: {
            appointmentCount: number;
            labOrderCount: number;
            prescriptionCount: number;
            latestAppointmentAt: Date | null;
            latestLabResultAt: Date | null;
            latestPrescriptionAt: Date | null;
        };
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        doctorId: string;
        status: AppointmentStatus;
        scheduledAt: Date | null;
        reason: string | null;
        preferredDateFrom: Date | null;
        preferredDateTo: Date | null;
        preferredTimeNote: string | null;
        requiresLab: boolean;
        labFlowLocked: boolean;
    }[]>;
    confirmByDoctor(doctorId: string, appointmentId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        doctorId: string;
        status: AppointmentStatus;
        scheduledAt: Date | null;
        reason: string | null;
        preferredDateFrom: Date | null;
        preferredDateTo: Date | null;
        preferredTimeNote: string | null;
        requiresLab: boolean;
        labFlowLocked: boolean;
    }>;
    scheduleByDoctor(doctorId: string, appointmentId: string, scheduledAt: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        doctorId: string;
        status: AppointmentStatus;
        scheduledAt: Date | null;
        reason: string | null;
        preferredDateFrom: Date | null;
        preferredDateTo: Date | null;
        preferredTimeNote: string | null;
        requiresLab: boolean;
        labFlowLocked: boolean;
    }>;
    callByDoctor(doctorId: string, appointmentId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        doctorId: string;
        status: AppointmentStatus;
        scheduledAt: Date | null;
        reason: string | null;
        preferredDateFrom: Date | null;
        preferredDateTo: Date | null;
        preferredTimeNote: string | null;
        requiresLab: boolean;
        labFlowLocked: boolean;
    }>;
    markInVisitByDoctor(doctorId: string, appointmentId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        doctorId: string;
        status: AppointmentStatus;
        scheduledAt: Date | null;
        reason: string | null;
        preferredDateFrom: Date | null;
        preferredDateTo: Date | null;
        preferredTimeNote: string | null;
        requiresLab: boolean;
        labFlowLocked: boolean;
    }>;
    markExamDoneByDoctor(doctorId: string, appointmentId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        doctorId: string;
        status: AppointmentStatus;
        scheduledAt: Date | null;
        reason: string | null;
        preferredDateFrom: Date | null;
        preferredDateTo: Date | null;
        preferredTimeNote: string | null;
        requiresLab: boolean;
        labFlowLocked: boolean;
    }>;
    closeByDoctor(doctorId: string, appointmentId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        doctorId: string;
        status: AppointmentStatus;
        scheduledAt: Date | null;
        reason: string | null;
        preferredDateFrom: Date | null;
        preferredDateTo: Date | null;
        preferredTimeNote: string | null;
        requiresLab: boolean;
        labFlowLocked: boolean;
    }>;
    cancelByDoctor(doctorId: string, appointmentId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        doctorId: string;
        status: AppointmentStatus;
        scheduledAt: Date | null;
        reason: string | null;
        preferredDateFrom: Date | null;
        preferredDateTo: Date | null;
        preferredTimeNote: string | null;
        requiresLab: boolean;
        labFlowLocked: boolean;
    }>;
    cancelByPatient(patientId: string, appointmentId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        patientId: string;
        doctorId: string;
        status: AppointmentStatus;
        scheduledAt: Date | null;
        reason: string | null;
        preferredDateFrom: Date | null;
        preferredDateTo: Date | null;
        preferredTimeNote: string | null;
        requiresLab: boolean;
        labFlowLocked: boolean;
    }>;
    private updateByDoctorTransition;
    private getAppointmentOrThrow;
    private assertDoctorOwnership;
    private transitionOrThrow;
    private assertCloseAllowed;
}
